# Generated by Django 5.0.3 on 2024-04-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GAL�XIA', 'Gal�xia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
